### ISSUE TITLE
Support for Linux 20.04

### ISSUE THREAD

**Issue by ranjitkathiriya** [lips-hci/ae400-realsense-sdk#5]
Hello there,

When are you planning to support Linux 20.04 and ros2 Foxy, ros1 noetic?

**Comment by ranjitkathiriya** [comment]
Any update on support?

**Comment by ranjitkathiriya** [comment]
Any update on support?

**Comment by LIPS-HCI-FAE** [comment]
Hi  Ranjitkathiriya,

It's on the way, we will release a new version at the end of this month.
Please be patient, thanks.

> Hello there,
> 
> When are you planning to support Linux 20.04 and ros2 Foxy, ros1 noetic?

**Comment by ranjitkathiriya** [comment]
Thanks for this comment, I hope the new version will be easy to install and every step of the installation will be well documented. 

Thanks, once again for helping.

**Comment by ranjitkathiriya** [comment]
Hello there,

To follow up,

 Any update on support for ros noetic and Ubuntu 20.04?

**Comment by LIPS-HCI-FAE** [comment]
Hi Ranjitkathiriya,

We are sorry, the new SDK release is delay.
This is a big update and we have made many changes. As a result, many unexpected errors occurred. 
Our group are now working hard to fix them.
The new release date will be postponed to the end of October.
Thank you again for your patience.


Best Regards,

Nest

**Comment by ranjitkathiriya** [comment]
https://github.com/lips-hci/ae400-realsense-sdk/releases/tag/AE400_v1.0.0.3_rs2.36.0 

This is working fine in ubuntu 20.04.
