### ISSUE TITLE
what is the default account and password for http://[camera_IP]

### ISSUE THREAD

**Issue by ranjitkathiriya** [lips-hci/ae400-realsense-sdk#8]
Hello there,

Can you please! help me with what's the default account and password for the camera is? Currently, I and camera are on the same network and I want to access the camera FW page and I am not able to get in because I don't have a camera pass and account. I will drop a screenshot for a detailed understanding. 

![Screenshot from 2021-11-02 07-47-20](https://user-images.githubusercontent.com/12687608/139806582-ebc995d7-2e91-421c-9939-42dad01a3209.png)

**Comment by LIPS-HCI-FAE** [comment]
Hi Ranjit,

Please try the default setting.
Account: admin
password: LIPS

**Comment by ranjitkathiriya** [comment]
Thanks for helping!
